// Plik: technologies.js

const technologies = {
    // ### BADANIA OGÓLNE (dla wszystkich sektorów) ###
    'COMMON_MANAGEMENT_1': { name: "Szkolenie Agile", description: "Wdrożenie zwinnych metodyk zarządzania projektami poprawia ogólną kondycję finansową firmy.", type: "wzmacnianie rozwoju", cost: 120, sector: 'common', icon: '🧑‍🏫', applyEffect: (stock) => { stock.financialHealth += 0.5; logEvent(`🎓 Wdrożenie Agile w ${stock.name} poprawia jej kondycję.`); } },
    'COMMON_MARKETING_1': { name: "Kampania Marketingowa Online", description: "Zwiększona obecność w mediach społecznościowych pozytywnie wpływa na postrzeganie marki i cenę akcji.", type: "wzmacnianie pozycji na rynku", cost: 150, sector: 'common', icon: '📈', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.03, 'positive'); logEvent(`📣 Udana kampania marketingowa podnosi wycenę ${stock.name}!`); } },
    'COMMON_LOGISTICS_1': { name: "Optymalizacja Logistyki", description: "Usprawnienie łańcucha dostaw zmniejsza wahania kursu związane z opóźnieniami.", type: "wzmacnianie ceny i zysków", cost: 180, sector: 'common', icon: '🚚', applyEffect: (stock) => { stock.volatilityFactor *= 0.95; } },
    'COMMON_HR_1': { name: "Program Benefitów Pracowniczych", description: "Wprowadzenie benefitów pozapłacowych zwiększa satysfakcję załogi i stabilność operacyjną firmy.", type: "wzmacnianie rozwoju", cost: 100, sector: 'common', icon: '🎁', applyEffect: (stock) => { stock.financialHealth += 0.25; stock.volatilityFactor *= 0.98; } },
    'COMMON_ECO_1': { name: "Certyfikat Eko-Odpowiedzialności", description: "Uzyskanie certyfikatu ekologicznego poprawia wizerunek firmy i przyciąga nowych inwestorów.", type: "wzmacnianie pozycji na rynku", cost: 200, sector: 'common', icon: '🌿', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.04, 'positive'); } },
    'COMMON_IT_1': { name: "System ERP", description: "Wdrożenie zintegrowanego systemu planowania zasobów przedsiębiorstwa zwiększa efektywność.", type: "wzmacnianie rozwoju", cost: 300, sector: 'common', icon: '💻', applyEffect: (stock) => { stock.financialHealth += 1.0; } },
    'COMMON_FINANCE_1': { name: "Zaawansowany Audyt Finansowy", description: "Przeprowadzenie dogłębnego audytu pozwala zoptymalizować koszty i zwiększyć rentowność.", type: "wzmacnianie ceny i zysków", cost: 220, sector: 'common', icon: '💰', applyEffect: (stock) => { stock.financialHealth += 0.5; stock.volatilityFactor *= 0.97; } },
    'COMMON_SECURITY_1': { name: "Systemy Cyberbezpieczeństwa", description: "Nowoczesne systemy ochrony danych zmniejszają ryzyko kryzysów wizerunkowych i kar finansowych.", type: "wzmacnianie rozwoju", cost: 280, sector: 'common', icon: '🛡️', applyEffect: (stock) => { stock.volatilityFactor *= 0.92; } },
    'COMMON_AUTOMATION_1': { name: "Automatyzacja Procesów Biznesowych", description: "Automatyzacja powtarzalnych zadań biurowych obniża koszty i przyspiesza działanie firmy.", type: "wzmacnianie ceny i zysków", cost: 350, sector: 'common', icon: '🤖', applyEffect: (stock) => { stock.financialHealth += 1.2; } },
    'COMMON_LEGAL_1': { name: "Optymalizacja Podatkowa", description: "Nowa strategia podatkowa pozwala na legalne obniżenie obciążeń fiskalnych, co zwiększa zysk netto.", type: "wzmacnianie ceny i zysków", cost: 400, sector: 'common', icon: '🧾', applyEffect: (stock) => { stock.financialHealth += 1.5; } },
    'COMMON_DATA_1': { name: "Analityka Big Data", description: "Wdrożenie narzędzi do analizy dużych zbiorów danych pozwala lepiej przewidywać trendy rynkowe.", type: "wzmacnianie pozycji na rynku", cost: 320, sector: 'common', icon: '📊', applyEffect: (stock) => { stock.volatilityFactor *= 0.90; } },
    'COMMON_EXPANSION_1': { name: "Badanie Rynków Zagranicznych", description: "Analiza potencjału eksportowego otwiera drzwi do przyszłej ekspansji i nowych źródeł przychodu.", type: "wzmacnianie rozwoju", cost: 250, sector: 'common', icon: '🌍', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.05, 'positive'); } },

    // ### BADANIA SEKTOROWE (9 TECHNOLOGII NA SEKTOR) ###

    // Przemysł
    'INDUSTRY_STEEL_1': { name: "Wzmocniona Stal", icon: '🔩', description: "Nowy stop stali jest lżejszy i bardziej wytrzymały.", type: "wzmacnianie ceny i zysków", cost: 200, sector: 'Przemysł', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.04, 'positive'); } },
    'INDUSTRY_EXCAVATOR_1': { name: "Nowoczesne Koparki", icon: '🏗️', description: "Większa wydajność maszyn budowlanych przyspiesza realizację kontraktów.", type: "wzmacnianie rozwoju", cost: 220, sector: 'Przemysł', applyEffect: (stock) => { stock.financialHealth += 1.0; } },
    'INDUSTRY_PLASTAL_1': { name: "Plastal", icon: '🧱', description: "Opatentowanie nowego, ultralekkiego kompozytu otwiera rynek premium.", type: "wzmacnianie ceny i zysków", cost: 300, sector: 'Przemysł', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.08, 'positive'); } },
    'INDUSTRY_LOGISTICS_1': { name: "Logistyka Just-In-Time", icon: '📦', description: "Perfekcyjna logistyka redukuje koszty magazynowania.", type: "wzmacnianie rozwoju", cost: 180, sector: 'Przemysł', applyEffect: (stock) => { stock.financialHealth += 0.8; } },
    'INDUSTRY_ROBO_1': { name: "Roboinżynieria", icon: '🦾', description: "Automatyzacja linii produkcyjnej zwiększa wydajność i jakość.", type: "wzmacnianie ceny i zysków", cost: 400, sector: 'Przemysł', applyEffect: (stock) => { stock.financialHealth += 1.2; stock.volatilityFactor *= 0.95; } },
    'INDUSTRY_TRAINING_1': { name: "Szkolenia Pracowników", icon: '👷', description: "Podniesienie kwalifikacji załogi poprawia bezpieczeństwo i efektywność.", type: "wzmacnianie rozwoju", cost: 150, sector: 'Przemysł', applyEffect: (stock) => { stock.financialHealth += 0.5; } },
    'INDUSTRY_QUANTUM_BARRACKS_1': { name: "Baraki Kwantowe", icon: '🌌', description: "Zastosowanie fizyki kwantowej do... budowy baraków? Brzmi innowacyjnie.", type: "wzmacnianie pozycji na rynku", cost: 500, sector: 'Przemysł', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.10, 'positive'); } },
    'INDUSTRY_SUPERMETAL_1': { name: "Supermetal", icon: '✨', description: "Odkrycie stopu o niemal niezniszczalnych właściwościach.", type: "wzmacnianie ceny i zysków", cost: 700, sector: 'Przemysł', applyEffect: (stock) => { stock.volatilityFactor *= 0.7; applyPriceEffect(stock.symbol, 0.15, 'positive'); } },
    'INDUSTRY_TRUCK_1': { name: "Powiększone Ciężarówki", icon: '🚛', description: "Zwiększenie ładowności floty transportowej o 15%. Proste i skuteczne.", type: "wzmacnianie rozwoju", cost: 240, sector: 'Przemysł', applyEffect: (stock) => { stock.financialHealth += 1.1; } },

    // Bankowość
    'BANKING_EWALLET_1': { name: "E-Bankowość Mobilna", icon: '📱', description: "Nowa, intuicyjna aplikacja mobilna przyciąga młodszych klientów.", type: "wzmacnianie pozycji na rynku", cost: 250, sector: 'Bankowość', applyEffect: (stock) => { stock.financialHealth += 0.75; } },
    'BANKING_CRYPTO_1': { name: "Integracja z Kryptowalutami", icon: '₿', description: "Możliwość handlu kryptowalutami przyciąga nowych, ryzykujących inwestorów.", type: "wzmacnianie pozycji na rynku", cost: 350, sector: 'Bankowość', applyEffect: (stock) => { stock.volatilityFactor *= 1.2; applyPriceEffect(stock.symbol, 0.05, 'positive');} },
    'BANKING_AI_ADVISOR_1': { name: "Doradca Inwestycyjny AI", icon: '🤖', description: "Automatyczny doradca pomaga klientom w zarządzaniu portfelem, zwiększając przychody z opłat.", type: "wzmacnianie ceny i zysków", cost: 400, sector: 'Bankowość', applyEffect: (stock) => { stock.financialHealth += 1.5; } },
    'BANKING_SECURITY_2': { name: "Sejfy w Innym Wymiarze", icon: '🌀', description: "Przełomowa, kwantowa technologia zabezpieczeń staje się legendą na rynku.", type: "wzmacnianie pozycji na rynku", cost: 500, sector: 'Bankowość', applyEffect: (stock) => { stock.volatilityFactor *= 0.8; stock.financialHealth += 1.0; } },
    'BANKING_PAPER_1': { name: "Lepszy Papier do Banknotów", icon: '💵', description: "Opracowanie trwalszego i bezpieczniejszego materiału na banknoty.", type: "wzmacnianie rozwoju", cost: 180, sector: 'Bankowość', applyEffect: (stock) => { stock.financialHealth += 0.6; } },
    'BANKING_PRINTER_1': { name: "Drukarki Pieniędzy", icon: '🖨️', description: "Usprawnienie procesu druku banknotów. Plotki mówią, że czasem się 'zacina' i drukuje za dużo...", type: "wzmacnianie ceny i zysków", cost: 280, sector: 'Bankowość', applyEffect: (stock) => { stock.financialHealth += 1.0; } },
    'BANKING_SONIC_1': { name: "Bankowość Elektrosoniczna", icon: '🔊', description: "Autoryzacja transakcji za pomocą unikalnego tonu głosu klienta.", type: "wzmacnianie pozycji na rynku", cost: 320, sector: 'Bankowość', applyEffect: (stock) => { stock.financialHealth += 0.9; } },
    'BANKING_CRASH_AI_1': { name: "AI Przewidujące Krachy", icon: '🔮', description: "System wczesnego ostrzegania przed kryzysami, co znacząco stabilizuje portfel banku.", type: "wzmacnianie rozwoju", cost: 600, sector: 'Bankowość', applyEffect: (stock) => { stock.volatilityFactor *= 0.75; } },
    'BANKING_UNLIMITED_CARD_1': { name: "Nielimitowane Karty Kredytowe", icon: '💳', description: "Oferta kart kredytowych bez limitu dla najbogatszych klientów. Bardzo dochodowe, bardzo ryzykowne.", type: "wzmacnianie ceny i zysków", cost: 450, sector: 'Bankowość', applyEffect: (stock) => { stock.financialHealth += 2.0; stock.volatilityFactor *= 1.3; } },
    
    // Żywność
    'FOOD_ECO_PACKAGING_1': { name: "Ekoplastik", icon: '♻️', description: "Biodegradowalne opakowania poprawiają wizerunek firmy.", type: "wzmacnianie pozycji na rynku", cost: 160, sector: 'Żywność', applyEffect: (stock) => { stock.financialHealth += 0.4; } },
    'FOOD_TASTER_1': { name: "Automatyczni Testerzy Żywności", icon: '🧪', description: "System AI do kontroli jakości eliminuje ryzyko wadliwych partii produktu.", type: "wzmacnianie rozwoju", cost: 200, sector: 'Żywność', applyEffect: (stock) => { stock.volatilityFactor *= 0.9; } },
    'FOOD_HYDRO_1': { name: "Baseny Hydroponiczne", icon: '🌱', description: "Własne uprawy hydroponiczne uniezależniają firmę od wahań cen na rynku rolnym.", type: "wzmacnianie ceny i zysków", cost: 300, sector: 'Żywność', applyEffect: (stock) => { stock.financialHealth += 1.0; stock.volatilityFactor *= 0.92; } },
    'FOOD_VITAMIN_1': { name: "Sok Multiwitamina", icon: '🧃', description: "Wprowadzenie na rynek nowego, prozdrowotnego produktu staje się hitem sprzedażowym.", type: "wzmacnianie pozycji na rynku", cost: 220, sector: 'Żywność', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.06, 'positive'); } },
    'FOOD_NO_ROT_1': { name: "Niegnijąca Mąka", icon: '🍞', description: "Opatentowanie metody przechowywania, która rewolucjonizuje logistykę i zapasy.", type: "wzmacnianie rozwoju", cost: 280, sector: 'Żywność', applyEffect: (stock) => { stock.financialHealth += 1.2; } },
    'FOOD_EDIBLE_CUP_1': { name: "Jadalne Kubki", icon: '☕', description: "Innowacyjny, ekologiczny produkt, który staje się viralem w mediach.", type: "wzmacnianie pozycji na rynku", cost: 190, sector: 'Żywność', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.05, 'positive'); } },
    'FOOD_BOWL_1': { name: "Chlebowe Miski", icon: '🥣', description: "Wprowadzenie jadalnych misek do zup. Genialne w swojej prostocie.", type: "wzmacnianie pozycji na rynku", cost: 150, sector: 'Żywność', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.03, 'positive'); } },
    'FOOD_3D_MEAT_1': { name: "Mięso z Drukarki 3D", icon: '🥩', description: "Rozpoczęcie produkcji syntetycznego mięsa, które idealnie imituje prawdziwe.", type: "wzmacnianie cen i zysków", cost: 500, sector: 'Żywność', applyEffect: (stock) => { stock.financialHealth += 1.8; } },
    'FOOD_STUDENT_MIX_1': { name: "Mieszanka Studencka Premium", icon: '🥜', description: "Nowa, luksusowa wersja mieszanki studenckiej z rzadkimi orzechami. Hit w korporacjach.", type: "wzmacnianie ceny i zysków", cost: 120, sector: 'Żywność', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.02, 'positive'); } },

    // Gaming
    'GAMING_CONSOLE_1': { name: "Nowa Konsola", icon: '🎮', description: "Wypuszczenie własnej konsoli tworzy zamknięty, dochodowy ekosystem.", type: "wzmacnianie pozycji na rynku", cost: 1000, sector: 'Gaming', applyEffect: (stock) => { stock.financialHealth += 3; applyPriceEffect(stock.symbol, 0.20, 'positive'); } },
    'GAMING_VR_1': { name: "Gry na Okulary VR", icon: '🕶️', description: "Wejście na nową, obiecującą platformę VR przyciąga entuzjastów technologii.", type: "wzmacnianie rozwoju", cost: 300, sector: 'Gaming', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.07, 'positive'); } },
    'GAMING_ADDICTION_1': { name: "System Uzależniania Graczy", icon: '🎰', description: "Kontrowersyjny, ale skuteczny system pętli behawioralnych maksymalizuje przychody.", type: "wzmacnianie ceny i zysków", cost: 400, sector: 'Gaming', applyEffect: (stock) => { stock.financialHealth += 2.0; stock.volatilityFactor *= 1.1; } },
    'GAMING_SLEEP_1': { name: "Granie Przez Sen", icon: '😴', description: "Technologia pozwalająca na zdobywanie postępów w grze podczas snu. Gracze to kochają.", type: "wzmacnianie pozycji na rynku", cost: 600, sector: 'Gaming', applyEffect: (stock) => { stock.financialHealth += 1.5; } },
    'GAMING_ENGINE_1': { name: "Własny Silnik Graficzny", icon: '🖼️', description: "Stworzenie własnego silnika uniezależnia od zewnętrznych firm i obniża koszty.", type: "wzmacnianie rozwoju", cost: 500, sector: 'Gaming', applyEffect: (stock) => { stock.financialHealth += 1.0; stock.volatilityFactor *= 0.9; } },
    'GAMING_CLOUD_1': { name: "Granie w Chmurze", icon: '☁️', description: "Uruchomienie własnej platformy do streamingu gier otwiera nowe źródło subskrypcji.", type: "wzmacnianie ceny i zysków", cost: 700, sector: 'Gaming', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.15, 'positive'); } },
    'GAMING_AI_QUEST_1': { name: "AI Generujące Questy", icon: '✍️', description: "System AI, który tworzy nieskończoną liczbę zadań dla graczy, utrzymując ich zaangażowanie.", type: "wzmacnianie pozycji na rynku", cost: 450, sector: 'Gaming', applyEffect: (stock) => { stock.financialHealth += 1.2; } },
    'GAMING_DREAM_MICRO_1': { name: "Mikrotransakcje w Snach", icon: '🌙', description: "Gracze mogą kupować przedmioty we śnie. Zyski są nierealne.", type: "wzmacnianie ceny i zysków", cost: 900, sector: 'Gaming', applyEffect: (stock) => { stock.financialHealth += 4.0; } },
    'GAMING_PORTABLE_PAD_1': { name: "Przenośne Pady", icon: '🕹️', description: "Kompaktowe, wysokiej jakości kontrolery do gier mobilnych stają się rynkowym hitem.", type: "wzmacnianie pozycji na rynku", cost: 250, sector: 'Gaming', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.06, 'positive'); } },

    // Technologia
    'TECH_CLOUD_2': { name: "Chmura w Chmurze", icon: '☁️', description: "Abstrakcyjna optymalizacja infrastruktury chmurowej, która (podobno) działa.", type: "wzmacnianie rozwoju", cost: 300, sector: 'Technologia', applyEffect: (stock) => { stock.financialHealth += 1.0; } },
    'TECH_ZERO_G_1': { name: "Serwery w Stanie Nieważkości", icon: '🛰️', description: "Przechowywanie danych na orbicie zmniejsza koszty chłodzenia i jest bardzo medialne.", type: "wzmacnianie pozycji na rynku", cost: 800, sector: 'Technologia', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.18, 'positive'); } },
    'TECH_PATENT_1': { name: "Nowe Patenty", icon: '⚖️', description: "Zabezpieczenie kluczowych technologii patentami generuje stały dochód z licencji.", type: "wzmacnianie ceny i zysków", cost: 400, sector: 'Technologia', applyEffect: (stock) => { stock.financialHealth += 1.5; } },
    'TECH_AGENT_AI_1': { name: "Agenci AI", icon: '🤖', description: "Autonomiczni agenci AI, którzy samodzielnie piszą i sprzedają oprogramowanie.", type: "wzmacnianie ceny i zysków", cost: 1200, sector: 'Technologia', applyEffect: (stock) => { stock.financialHealth += 4; } },
    'TECH_FAB_1': { name: "Fabryki Komponentów", icon: '🏭', description: "Budowa własnej fabryki półprzewodników uniezależnia od azjatyckich dostawców.", type: "wzmacnianie rozwoju", cost: 900, sector: 'Technologia', applyEffect: (stock) => { stock.volatilityFactor *= 0.7; stock.financialHealth += 2.0; } },
    'TECH_QUANTUM_1': { name: "Komputery Kwantowe", icon: '⚛️', description: "Przełom w obliczeniach kwantowych daje firmie ogromną przewagę technologiczną.", type: "wzmacnianie pozycji na rynku", cost: 1500, sector: 'Technologia', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.30, 'positive'); } },
    'TECH_HOLO_1': { name: "Holograficzne Telekonferencje", icon: '👨‍🚀', description: "System do telekonferencji, który wyświetla rozmówców jako trójwymiarowe hologramy.", type: "wzmacnianie pozycji na rynku", cost: 600, sector: 'Technologia', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.12, 'positive'); } },
    'TECH_SELF_WRITE_1': { name: "Samospisujące się Oprogramowanie", icon: '✍️', description: "Stworzenie kodu, który sam się rozwija i naprawia. Przerażające i genialne.", type: "wzmacnianie rozwoju", cost: 2000, sector: 'Technologia', applyEffect: (stock) => { stock.financialHealth += 5; } },
    'TECH_NEURAL_1': { name: "Neuralink-as-a-Service", icon: '🧠', description: "Platforma chmurowa do zarządzania implantami neuronowymi. Przyszłość jest teraz.", type: "wzmacnianie ceny i zysków", cost: 1800, sector: 'Technologia', applyEffect: (stock) => { stock.financialHealth += 3; applyPriceEffect(stock.symbol, 0.20, 'positive'); } },
    
    // Nieruchomości
    'REALTY_SMART_HOME_1': { name: "System Smart Home", icon: '🏠', description: "Integracja mieszkań z systemem inteligentnego domu staje się standardem w ofercie.", type: "wzmacnianie ceny i zysków", cost: 250, sector: 'Nieruchomości', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.05, 'positive'); } },
    'REALTY_MODULAR_1': { name: "Budownictwo Modułowe", icon: '📦', description: "Wdrożenie technologii budowy z prefabrykatów skraca czas i obniża koszty inwestycji.", type: "wzmacnianie rozwoju", cost: 350, sector: 'Nieruchomości', applyEffect: (stock) => { stock.financialHealth += 1.5; } },
    'REALTY_3DPRINT_1': { name: "Domy z Drukarki 3D", icon: '🖨️', description: "Zastosowanie druku 3D do wznoszenia budynków rewolucjonizuje rynek budowlany.", type: "wzmacnianie rozwoju", cost: 600, sector: 'Nieruchomości', applyEffect: (stock) => { stock.financialHealth += 2.0; stock.volatilityFactor *= 0.85; } },
    'REALTY_GREEN_ROOF_1': { name: "Zielone Dachy", icon: '🌿', description: "Standardowe wyposażanie budynków w zielone dachy i systemy odzysku wody.", type: "wzmacnianie pozycji na rynku", cost: 200, sector: 'Nieruchomości', applyEffect: (stock) => { stock.financialHealth += 0.5; applyPriceEffect(stock.symbol, 0.03, 'positive'); } },
    'REALTY_METAVERSE_1': { name: "Wirtualne Nieruchomości", icon: '🌐', description: "Sprzedaż działek i apartamentów w popularnym metawersum jako nowa gałąź biznesu.", type: "wzmacnianie ceny i zysków", cost: 400, sector: 'Nieruchomości', applyEffect: (stock) => { stock.financialHealth += 1.0; stock.volatilityFactor *= 1.2; } },
    'REALTY_ANTIGRAV_1': { name: "Antygrawitacyjne Fundamenty", icon: '🚀', description: "Pozwalają budować na dowolnym terenie. Fizycy twierdzą, że to niemożliwe, ale działa.", type: "wzmacnianie pozycji na rynku", cost: 1500, sector: 'Nieruchomości', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.35, 'positive'); } },
    'REALTY_UNDERGROUND_1': { name: "Luksusowe Bunkry", icon: ' bunkers.png', description: "Budowa luksusowych, samowystarczalnych bunkrów dla najbogatszych.", type: "wzmacnianie ceny i zysków", cost: 700, sector: 'Nieruchomości', applyEffect: (stock) => { stock.financialHealth += 2.2; } },
    'REALTY_AI_ARCHITECT_1': { name: "Architekt AI", icon: '🏛️', description: "AI, która projektuje zoptymalizowane i piękne budynki w ułamku sekundy.", type: "wzmacnianie rozwoju", cost: 450, sector: 'Nieruchomości', applyEffect: (stock) => { stock.financialHealth += 1.8; } },
    'REALTY_DYNAMIC_WALLS_1': { name: "Dynamiczne Ściany", icon: '🧱', description: "System przesuwnych ścian pozwalający na dowolną rekonfigurację mieszkania.", type: "wzmacnianie pozycji na rynku", cost: 380, sector: 'Nieruchomości', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.07, 'positive'); } },

    // Energia
    'ENERGY_FUSION_1': { name: "Reaktor Fuzyjny", icon: '☀️', description: "Przełom w badaniach nad fuzją jądrową obiecuje tanią, czystą energię.", type: "wzmacnianie pozycji na rynku", cost: 2000, sector: 'Energia', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.50, 'positive'); stock.financialHealth += 2; } },
    'ENERGY_BATTERY_1': { name: "Magazyny Bateryjne", icon: '🔋', description: "Rozwój technologii magazynowania energii stabilizuje sieć i zyski.", type: "wzmacnianie ceny i zysków", cost: 400, sector: 'Energia', applyEffect: (stock) => { stock.volatilityFactor *= 0.8; } },
    'ENERGY_WIRELESS_1': { name: "Bezprzewodowy Przesył Energii", icon: '📡', description: "Technologia przesyłu energii na odległość eliminuje potrzebę budowy drogich linii energetycznych.", type: "wzmacnianie pozycji na rynku", cost: 1200, sector: 'Energia', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.30, 'positive'); } },
    'ENERGY_SMART_GRID_1': { name: "Inteligentna Sieć (Smart Grid)", icon: '🌐', description: "Sieć energetyczna, która sama zarządza popytem i podażą, minimalizując straty.", type: "wzmacnianie rozwoju", cost: 500, sector: 'Energia', applyEffect: (stock) => { stock.financialHealth += 2.0; stock.volatilityFactor *= 0.88; } },
    'ENERGY_BLACK_HOLE_1': { name: "Energia z Osobliwości", icon: '⚫', description: "Niezwykle wydajne, choć nieco niepokojące źródło energii.", type: "wzmacnianie ceny i zysków", cost: 3000, sector: 'Energia', applyEffect: (stock) => { stock.financialHealth += 10; } },
    'ENERGY_GEO_1': { name: "Geotermia Głębinowa", icon: '🌋', description: "Odwierty do jądra Ziemi pozwalają na pozyskanie niemal nieskończonej energii.", type: "wzmacnianie rozwoju", cost: 800, sector: 'Energia', applyEffect: (stock) => { stock.financialHealth += 3.0; } },
    'ENERGY_KINETIC_1': { name: "Płytki Kinetyczne", icon: '🚶', description: "Płytki chodnikowe, które generują energię z kroków przechodniów.", type: "wzmacnianie pozycji na rynku", cost: 300, sector: 'Energia', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.05, 'positive'); } },
    'ENERGY_SOLAR_PAINT_1': { name: "Farba Fotowoltaiczna", icon: '🎨', description: "Farba, którą można pomalować dowolną powierzchnię, zamieniając ją w panel słoneczny.", type: "wzmacnianie ceny i zysków", cost: 600, sector: 'Energia', applyEffect: (stock) => { stock.financialHealth += 1.5; applyPriceEffect(stock.symbol, 0.10, 'positive'); } },
    'ENERGY_ALGAE_1': { name: "Biopaliwo z Alg", icon: '🌿', description: "Wydajne i ekologiczne paliwo produkowane w bioreaktorach z alg.", type: "wzmacnianie rozwoju", cost: 450, sector: 'Energia', applyEffect: (stock) => { stock.financialHealth += 1.2; } },
    
    // Chemia
    'CHEM_GRAPHENE_1': { name: "Produkcja Grafenu", icon: '✒️', description: "Opanowanie masowej produkcji grafenu otwiera drzwi do rewolucji materiałowej.", type: "wzmacnianie pozycji na rynku", cost: 900, sector: 'Chemia', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.25, 'positive'); } },
    'CHEM_SELF_HEAL_1': { name: "Polimery Samonaprawiające", icon: '🩹', description: "Tworzywa sztuczne, które same 'leczą' pęknięcia i zarysowania.", type: "wzmacnianie ceny i zysków", cost: 500, sector: 'Chemia', applyEffect: (stock) => { stock.financialHealth += 1.5; applyPriceEffect(stock.symbol, 0.05, 'positive'); } },
    'CHEM_SMART_PAINT_1': { name: "Inteligentne Farby", icon: '🎨', description: "Farby, które zmieniają kolor w zależności od temperatury lub nastroju.", type: "wzmacnianie pozycji na rynku", cost: 300, sector: 'Chemia', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.08, 'positive'); } },
    'CHEM_ALCHEMY_1': { name: "Alchemia Stosowana", icon: '🧪', description: "Transmutacja ołowiu w złoto. Wciąż na etapie eksperymentalnym, ale rynek jest podekscytowany.", type: "wzmacnianie ceny i zysków", cost: 2500, sector: 'Chemia', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.60, 'positive'); } },
    'CHEM_WATER_FUEL_1': { name: "Paliwo z Wody", icon: '💧', description: "Opatentowanie wydajnego katalizatora do elektrolizy wody.", type: "wzmacnianie rozwoju", cost: 1200, sector: 'Chemia', applyEffect: (stock) => { stock.financialHealth += 4.0; } },
    'CHEM_CO2_CAPTURE_1': { name: "Wychwyt CO2 z Atmosfery", icon: '☁️', description: "Technologia, która zamienia dwutlenek węgla w użyteczne polimery. Niezwykle dochodowa i proekologiczna.", type: "wzmacnianie pozycji na rynku", cost: 800, sector: 'Chemia', applyEffect: (stock) => { stock.financialHealth += 2.0; applyPriceEffect(stock.symbol, 0.15, 'positive'); } },
    'CHEM_PLASTIC_EATING_1': { name: "Enzymy trawiące plastik", icon: '🗑️', description: "Odkrycie enzymów, które w szybkim tempie rozkładają odpady z tworzyw sztucznych.", type: "wzmacnianie rozwoju", cost: 600, sector: 'Chemia', applyEffect: (stock) => { stock.financialHealth += 2.5; } },
    'CHEM_AERO_GEL_1': { name: "Produkcja Aerożelu", icon: '🧊', description: "Uruchomienie produkcji najlżejszego materiału stałego na świecie o niezwykłych właściwościach izolacyjnych.", type: "wzmacnianie ceny i zysków", cost: 400, sector: 'Chemia', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.10, 'positive'); } },
    'CHEM_MED_POLYMER_1': { name: "Polimery Medyczne", icon: '❤️', description: "Stworzenie biokompatybilnych polimerów do produkcji implantów i protez.", type: "wzmacnianie pozycji na rynku", cost: 450, sector: 'Chemia', applyEffect: (stock) => { stock.financialHealth += 1.2; } },
    
    // Dobra konsumpcyjne
    'CONSUMER_3DPRINT_1': { name: "Druk 3D na Życzenie", icon: '🖨️', description: "Możliwość personalizacji produktów za pomocą druku 3D przyciąga klientów premium.", type: "wzmacnianie pozycji na rynku", cost: 280, sector: 'Dobra konsumpcyjne', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.06, 'positive'); } },
    'CONSUMER_SELF_CLEAN_1': { name: "Samoczyszczące Ubrania", icon: '👕', description: "Nanotechnologia w tkaninach, która odpycha brud i wodę.", type: "wzmacnianie ceny i zysków", cost: 400, sector: 'Dobra konsumpcyjne', applyEffect: (stock) => { stock.financialHealth += 1.5; } },
    'CONSUMER_ETERNAL_BULB_1': { name: "Wieczna Żarówka", icon: '💡', description: "Żarówka, która nigdy się nie przepala. Jednorazowy zakup, ale ogromny prestiż.", type: "wzmacnianie pozycji na rynku", cost: 600, sector: 'Dobra konsumpcyjne', applyEffect: (stock) => { stock.volatilityFactor *= 0.8; applyPriceEffect(stock.symbol, 0.10, 'positive'); } },
    'CONSUMER_SMART_PACK_1': { name: "Inteligentne Opakowania", icon: '📦', description: "Opakowania, które informują o świeżości produktu lub same zamawiają uzupełnienie.", type: "wzmacnianie rozwoju", cost: 220, sector: 'Dobra konsumpcyjne', applyEffect: (stock) => { stock.financialHealth += 0.8; } },
    'CONSUMER_SCENT_1': { name: "Personalizowane Zapachy", icon: '👃', description: "System AI, który tworzy unikalne perfumy na podstawie preferencji klienta.", type: "wzmacnianie pozycji na rynku", cost: 320, sector: 'Dobra konsumpcyjne', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.07, 'positive'); } },
    'CONSUMER_SUSTAINABLE_1': { name: "Materiały z Recyklingu", icon: '♻️', description: "Pełne przejście na produkcję z materiałów pochodzących w 100% z recyklingu.", type: "wzmacnianie pozycji na rynku", cost: 250, sector: 'Dobra konsumpcyjne', applyEffect: (stock) => { stock.financialHealth += 0.5; } },
    'CONSUMER_TELEPORT_1': { name: "Teleportacja Produktów", icon: '🌀', description: "Natychmiastowa dostawa do domu. Technologia wciąż niestabilna, czasem zamiast tostera pojawia się pingwin.", type: "wzmacnianie ceny i zysków", cost: 2000, sector: 'Dobra konsumpcyjne', applyEffect: (stock) => { stock.financialHealth += 5.0; stock.volatilityFactor *= 1.5; } },
    'CONSUMER_LOYALTY_AI_1': { name: "Program Lojalnościowy AI", icon: '❤️', description: "AI, które personalizuje zniżki i nagrody, maksymalizując lojalność klientów.", type: "wzmacnianie rozwoju", cost: 380, sector: 'Dobra konsumpcyjne', applyEffect: (stock) => { stock.financialHealth += 1.2; } },
    'CONSUMER_UNIVERSAL_REMOTE_1': { name: "Uniwersalny Pilot", icon: '🎛️', description: "Jeden pilot do sterowania absolutnie wszystkim. Ostateczne rozwiązanie problemu pierwszego świata.", type: "wzmacnianie pozycji na rynku", cost: 420, sector: 'Dobra konsumpcyjne', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.10, 'positive'); } },
    
    // Usługi
    'SERVICES_DRONE_1': { name: "Dostawy Dronami", icon: '🛸', description: "Automatyzacja 'ostatniej mili' w dostawach rewolucjonizuje logistykę firmy.", type: "wzmacnianie rozwoju", cost: 450, sector: 'Usługi', applyEffect: (stock) => { stock.financialHealth += 1.8; } },
    'SERVICES_AI_LAWYER_1': { name: "Prawnik AI", icon: '⚖️', description: "AI, które analizuje dokumenty i przygotowuje pisma procesowe, obniżając koszty obsługi prawnej.", type: "wzmacnianie ceny i zysków", cost: 600, sector: 'Usługi', applyEffect: (stock) => { stock.financialHealth += 2.0; } },
    'SERVICES_AI_SUPPORT_1': { name: "Wsparcie Klienta AI", icon: '🎧', description: "Chatboty i voiceboty, które są nieodróżnialne od ludzi i rozwiązują 99% problemów.", type: "wzmacnianie rozwoju", cost: 400, sector: 'Usługi', applyEffect: (stock) => { stock.financialHealth += 1.5; } },
    'SERVICES_DIGITAL_TWIN_1': { name: "Cyfrowe Sobowtóry", icon: '👨‍💻', description: "Usługa tworzenia cyfrowych awatarów, które mogą uczestniczyć w spotkaniach za klienta.", type: "wzmacnianie pozycji na rynku", cost: 700, sector: 'Usługi', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.12, 'positive'); } },
    'SERVICES_PREDICTIVE_1': { name: "Konserwacja Predykcyjna", icon: '🔧', description: "Systemy, które przewidują awarie maszyn, zanim one nastąpią, oferowane jako usługa.", type: "wzmacnianie ceny i zysków", cost: 500, sector: 'Usługi', applyEffect: (stock) => { stock.volatilityFactor *= 0.85; stock.financialHealth += 1.0; } },
    'SERVICES_OUTSOURCE_DIMENSION_1': { name: "Outsourcing Międzywymiarowy", icon: '🌀', description: "Zlecanie zadań istotom z innych wymiarów. Taniej, ale komunikacja bywa trudna.", type: "wzmacnianie ceny i zysków", cost: 1500, sector: 'Usługi', applyEffect: (stock) => { stock.financialHealth += 6.0; } },
    'SERVICES_CLOUD_PLATFORM_1': { name: "Własna Platforma Chmurowa", icon: '☁️', description: "Stworzenie własnej infrastruktury chmurowej uniezależnia od gigantów i staje się nowym źródłem przychodu.", type: "wzmacnianie rozwoju", cost: 800, sector: 'Usługi', applyEffect: (stock) => { stock.financialHealth += 2.5; } },
    'SERVICES_SUBSCRIPTION_1': { name: "Model Subskrypcyjny", icon: '🔁', description: "Przejście z jednorazowych usług na model subskrypcyjny, zapewniający stały dopływ gotówki.", type: "wzmacnianie ceny i zysków", cost: 300, sector: 'Usługi', applyEffect: (stock) => { stock.volatilityFactor *= 0.9; } },
    'SERVICES_ON_DEMAND_1': { name: "Eksperci na Żądanie", icon: '💡', description: "Platforma łącząca firmy z wysoko wykwalifikowanymi ekspertami na godziny.", type: "wzmacnianie pozycji na rynku", cost: 350, sector: 'Usługi', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.07, 'positive'); } },
    
    // Turystyka
    'TOURISM_VR_1': { name: "Wirtualne Wycieczki", icon: '🌐', description: "Oferowanie wycieczek w wirtualnej rzeczywistości jako nowa gałąź przychodów.", type: "wzmacnianie ceny i zysków", cost: 320, sector: 'Turystyka', applyEffect: (stock) => { stock.financialHealth += 1.0; } },
    'TOURISM_SPACE_1': { name: "Turystyka Kosmiczna", icon: '🚀', description: "Organizacja lotów suborbitalnych dla najbogatszych klientów.", type: "wzmacnianie pozycji na rynku", cost: 2500, sector: 'Turystyka', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.70, 'positive'); } },
    'TOURISM_AI_PLANNER_1': { name: "Planer Podróży AI", icon: '🗺️', description: "AI, które tworzy idealnie spersonalizowane plany podróży, maksymalizując satysfakcję klientów.", type: "wzmacnianie rozwoju", cost: 400, sector: 'Turystyka', applyEffect: (stock) => { stock.financialHealth += 1.5; } },
    'TOURISM_UNDERWATER_HOTEL_1': { name: "Hotel Podwodny", icon: '🐠', description: "Budowa luksusowego hotelu na dnie oceanu. Ogromna atrakcja.", type: "wzmacnianie pozycji na rynku", cost: 1200, sector: 'Turystyka', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.25, 'positive'); } },
    'TOURISM_LOYALTY_1': { name: "Globalny Program Lojalnościowy", icon: '⭐', description: "Wspólny program lojalnościowy z liniami lotniczymi i hotelami na całym świecie.", type: "wzmacnianie pozycji na rynku", cost: 300, sector: 'Turystyka', applyEffect: (stock) => { stock.financialHealth += 0.8; } },
    'TOURISM_DYNAMIC_PRICING_1': { name: "Dynamiczne Wyceny", icon: '💲', description: "System AI, który w czasie rzeczywistym dostosowuje ceny wycieczek do popytu, maksymalizując zyski.", type: "wzmacnianie ceny i zysków", cost: 450, sector: 'Turystyka', applyEffect: (stock) => { stock.financialHealth += 1.8; } },
    'TOURISM_TRANSLATOR_1': { name: "Tłumacz Neuronowy", icon: '🗣️', description: "Urządzenie, które w czasie rzeczywistym tłumaczy rozmowy na dowolny język.", type: "wzmacnianie rozwoju", cost: 600, sector: 'Turystyka', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.10, 'positive'); } },
    'TOURISM_TIME_TRAVEL_1': { name: "Podróże w Czasie (Symulacje)", icon: '⏳', description: "Historyczne symulacje VR pozwalające 'odwiedzić' starożytny Rzym lub pole bitwy pod Grunwaldem.", type: "wzmacnianie pozycji na rynku", cost: 800, sector: 'Turystyka', applyEffect: (stock) => { stock.financialHealth += 1.2; applyPriceEffect(stock.symbol, 0.15, 'positive'); } },
    'TOURISM_ECO_1': { name: "Ekoturystyka", icon: '🌲', description: "Certyfikowane, neutralne dla środowiska wycieczki, które stają się nowym, modnym trendem.", type: "wzmacnianie rozwoju", cost: 280, sector: 'Turystyka', applyEffect: (stock) => { stock.financialHealth += 0.7; } },

    // Medycyna
    'MED_GENE_1': { name: "Terapie Genowe", icon: '🧬', description: "Przełom w personalizowanych terapiach genowych daje nadzieję milionom pacjentów.", type: "wzmacnianie pozycji na rynku", cost: 1800, sector: 'Medycyna', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.40, 'positive'); } },
    'MED_AI_DIAG_1': { name: "Diagnostyka AI", icon: '🩺', description: "System AI, który trafniej niż lekarze diagnozuje choroby ze zdjęć, rewolucjonizuje rynek.", type: "wzmacnianie rozwoju", cost: 600, sector: 'Medycyna', applyEffect: (stock) => { stock.financialHealth += 2.5; } },
    'MED_NANOBOTS_1': { name: "Nanoboty Naprawcze", icon: '🤖', description: "Mikroskopijne roboty krążące w krwiobiegu, które naprawiają uszkodzone komórki.", type: "wzmacnianie cen i zysków", cost: 2200, sector: 'Medycyna', applyEffect: (stock) => { stock.financialHealth += 5.0; } },
    'MED_REGEN_CAPSULE_1': { name: "Kapsuły Regeneracyjne", icon: '🛌', description: "Urządzenia, które w ciągu kilku godzin leczą złamania i poważne urazy.", type: "wzmacnianie rozwoju", cost: 1500, sector: 'Medycyna', applyEffect: (stock) => { stock.financialHealth += 4.0; } },
    'MED_ANTI_AGING_1': { name: "Odwracanie Starzenia", icon: '👶', description: "Terapia, która cofa zegar biologiczny. Skutki uboczne są... nieznane.", type: "wzmacnianie pozycji na rynku", cost: 3000, sector: 'Medycyna', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 1.0, 'positive'); } },
    'MED_3D_ORGANS_1': { name: "Druk Organów 3D", icon: '🖨️', description: "Możliwość 'wydrukowania' w pełni funkcjonalnej nerki lub serca na zamówienie.", type: "wzmacnianie rozwoju", cost: 1900, sector: 'Medycyna', applyEffect: (stock) => { stock.financialHealth += 6.0; } },
    'MED_ROBO_SURGEON_1': { name: "Zdalny Chirurg Robotyczny", icon: '🦾', description: "Robot, który pozwala najlepszym chirurgom na świecie operować pacjentów na odległość.", type: "wzmacnianie pozycji na rynku", cost: 800, sector: 'Medycyna', applyEffect: (stock) => { stock.volatilityFactor *= 0.8; } },
    'MED_CRYO_1': { name: "Krionika", icon: '🥶', description: "Usługa zamrażania pacjentów z nadzieją na ich ożywienie w przyszłości. Biznes z zerową liczbą reklamacji.", type: "wzmacnianie ceny i zysków", cost: 700, sector: 'Medycyna', applyEffect: (stock) => { stock.financialHealth += 2.0; } },
    'MED_TELEPATHY_1': { name: "Leczenie Telepatyczne", icon: '🧠', description: "Terapia dla pacjentów w śpiączce za pomocą interfejsu mózg-komputer. Przełom w neurologii.", type: "wzmacnianie rozwoju", cost: 900, sector: 'Medycyna', applyEffect: (stock) => { applyPriceEffect(stock.symbol, 0.20, 'positive'); } },
};

// --- 2. LOGIKA GENERATORÓW (BEZ ZMIAN) ---
// ... (cała reszta pliku, czyli wszystkie funkcje, pozostaje bez zmian) ...